
import { Bagel_Fat_One} from 'next/font/google'
import {Nav} from '../app/Components/Nav'
import '../app/globals.css'

const inter =   Bagel_Fat_One({ weight: ['400'],subsets:['latin-ext'] })

export const metadata = {
  title: 'BatBlogs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
        <Nav/>
        {children}
        </body>
    </html>
  )
}
